"""
Recommendation API endpoints.
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Dict, Any

from app.agents.recommendation_agent import RecommendationAgent
from app.db.user_profile import UserProfileManager
from app.core.logger import logger

router = APIRouter()


class RecommendRequest(BaseModel):
    """Recommendation request model."""
    user_id: str = "default"
    days: int = 3
    top_k: int = 5
    min_score: int = 0


class UpdateInterestsRequest(BaseModel):
    """Update user interests request."""
    user_id: str = "default"
    interests: List[str]


class SimilarArticlesRequest(BaseModel):
    """Similar articles request."""
    item_id: str
    top_k: int = 5


@router.post("/recommend")
async def get_recommendations(request: RecommendRequest):
    """
    Get personalized recommendations based on user interests.

    Returns:
    - Recommended articles
    - Recommendation reasons (generated by LLM)
    """
    try:
        logger.info(f"Generating recommendations for user: {request.user_id}")

        # Get user profile
        profile_manager = UserProfileManager()
        profile = profile_manager.get_profile(request.user_id)
        interests = profile.get("interests", [])

        if not interests:
            return {
                "message": "请先设置您的兴趣标签",
                "recommendations": [],
                "user_id": request.user_id
            }

        # Generate recommendations
        rec_agent = RecommendationAgent()
        result = rec_agent.recommend(
            interests=interests,
            days=request.days,
            top_k=request.top_k,
            min_score=request.min_score
        )

        logger.info(f"Generated {len(result.get('recommendations', []))} recommendations")

        return {
            **result,
            "user_id": request.user_id,
            "interests": interests
        }

    except Exception as e:
        logger.error(f"Recommendation error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/recommend/similar/{item_id}")
async def get_similar_articles(item_id: str, top_k: int = 5):
    """
    Get similar articles based on a given article.

    Args:
        item_id: Article ID
        top_k: Number of similar articles to return
    """
    try:
        logger.info(f"Finding similar articles for: {item_id}")

        rec_agent = RecommendationAgent()
        similar = rec_agent.recommend_similar(item_id, top_k=top_k)

        return {
            "item_id": item_id,
            "similar_articles": similar,
            "count": len(similar)
        }

    except Exception as e:
        logger.error(f"Similar articles error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/user/interests")
async def update_user_interests(request: UpdateInterestsRequest):
    """
    Update user interest tags.

    Args:
        user_id: User identifier
        interests: List of interest tags
    """
    try:
        logger.info(f"Updating interests for user {request.user_id}: {request.interests}")

        profile_manager = UserProfileManager()
        success = profile_manager.update_interests(request.interests, request.user_id)

        if not success:
            raise HTTPException(status_code=500, detail="Failed to update interests")

        profile = profile_manager.get_profile(request.user_id)

        return {
            "message": "兴趣标签已更新",
            "user_id": request.user_id,
            "interests": profile.get("interests", []),
            "updated_at": profile.get("updated_at")
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Update interests error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/user/profile/{user_id}")
async def get_user_profile(user_id: str = "default"):
    """
    Get user profile including interests and reading history.

    Args:
        user_id: User identifier
    """
    try:
        profile_manager = UserProfileManager()
        profile = profile_manager.get_profile(user_id)

        # Get recent reading history
        history = profile_manager.get_reading_history(user_id, limit=10)

        return {
            "user_id": user_id,
            "interests": profile.get("interests", []),
            "preferences": profile.get("preferences", {}),
            "reading_history": history,
            "created_at": profile.get("created_at"),
            "updated_at": profile.get("updated_at")
        }

    except Exception as e:
        logger.error(f"Get profile error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/user/history")
async def add_to_history(
    user_id: str,
    item_id: str,
    title: str,
    topic: str
):
    """
    Add article to user's reading history.

    Args:
        user_id: User identifier
        item_id: Article ID
        title: Article title
        topic: Article topic
    """
    try:
        logger.info(f"Adding article {item_id} to history for user {user_id}")

        profile_manager = UserProfileManager()
        success = profile_manager.add_to_history(
            item_id=item_id,
            title=title,
            topic=topic,
            user_id=user_id
        )

        if not success:
            raise HTTPException(status_code=500, detail="Failed to add to history")

        return {
            "message": "已添加到阅读历史",
            "user_id": user_id,
            "item_id": item_id
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Add to history error: {e}")
        raise HTTPException(status_code=500, detail=str(e))
